services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exchange-service
      MYSQL_USER: exchange-service
      MYSQL_PASSWORD: exchange-service
