info:
  name: Config Br
  type: http
  seq: 4

http:
  method: GET
  url: http://localhost:8888/greeting-service/br
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
