/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.brunoan99.app;

import dev.brunoan99.list.LinkedList;

import static dev.brunoan99.utilities.StringUtils.join;
import static dev.brunoan99.utilities.StringUtils.split;
import static dev.brunoan99.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
