spring:
  application:
    name: rest-with-spring-boot
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useTimezone=true&serverTimezone=UTC
    username: root
    password: rootpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
logging:
  level:
    dev.brunoan.rest_with_spring_boot_and_java: DEBUG

