package org.example.GettingToKnowTheLanguage.Generics;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.example.Utils.SubArticle;

public class TypeErasure implements SubArticle {
  public void execute() {
    new PotentialVulnerabilitiesWithNonReifiable().execute();
  }
}

class Node<T> {
  private T data;
  @SuppressWarnings("unused")
  private Node<T> next;

  public Node(T data, Node<T> next) {
    this.data = data;
    this.next = next;
  }

  public T getData() {
    return data;
  }
}
/*
 * Erasure to
 * public class Node {
 *
 * private Object data;
 * private Node next;
 *
 * public Node(Object data, Node next) {
 * this.data = data;
 * this.next = next;
 * }
 *
 * public Object getData() { return data; }
 * // ...
 * }
 */

class ErasureGenericMethods {
  @SuppressWarnings("null")
  public static <T> int count(T[] anArray, T elem) {
    int count = 0;
    for (T e : anArray)
      if (e.equals(elem))
        ++count;
    return count;
  }
  /*
   * Erasure to
   * public static int count(Object[] anArray, Object elem) {
   * int count = 0;
   * for (Object e : anArray)
   * if (e.equals(elem))
   * ++count;
   * return count;
   * }
   *
   */

  class Shape {
    /* ... */ }

  class Circle extends Shape {
    /* ... */ }

  class Rectangle extends Shape {
    /* ... */ }

  public static <T extends Shape> void draw(T shape) {
  }
  /*
   * Erasure to
   * public static void draw(Shape shape)
   */
}

class BridgeMethods {
  class Node {
    public Object data;

    public Node(Object data) {
      this.data = data;
    }

    public void setData(Object data) {
      System.out.println("Node.setData");
      this.data = data;
    }
  }

  class MyNode extends Node {
    public MyNode(Integer data) {
      super(data);
    }

    public void setData(Integer data) {
      System.out.println("MyNode.setData");
      super.setData(data);
    }
    /*
     * Bridge method generated by the compiler
     *
     * public void setData(Object data) {
     * setData((Integer) data);
     * }
     */
  }
}

class PotentialVulnerabilitiesWithNonReifiable {
  class ArrayBuilder {

    public static <T> void addToList(List<T> listArg, T... elements) {
      for (T x : elements) {
        listArg.add(x);
      }
    }

    public static void faultyMethod(List<String>... l) {
      Object[] objectArray = l; // Valid
      objectArray[0] = Arrays.asList(42);
      // String s = l[0].get(0); // ClassCastException thrown here
    }

  }

  public class HeapPollutionExample implements SubArticle {

    @SuppressWarnings("unchecked")
    public void execute() {

      List<String> stringListA = new ArrayList<String>();
      List<String> stringListB = new ArrayList<String>();

      ArrayBuilder.addToList(stringListA, "Seven", "Eight", "Nine");
      ArrayBuilder.addToList(stringListB, "Ten", "Eleven", "Twelve");
      List<List<String>> listOfStringLists = new ArrayList<List<String>>();
      ArrayBuilder.addToList(listOfStringLists,
          stringListA, stringListB);

      ArrayBuilder.faultyMethod(Arrays.asList("Hello!"), Arrays.asList("World!"));
    }
  }

  public void execute() {
    new HeapPollutionExample().execute();
  }
}
